version: '3.9'

services:
  api:
    container_name: you-sync-api
    build:
      context: ./
    ports:
      - 3333:3333
    image: api
    restart: unless-stopped
    environment:
      - PORT=3333
    
  